#!/usr/bin/env bash
# update-kit.sh — pull kit-owned changes from a newer kit version into this
# project, without ever touching project-owned paths.
#
# What "kit-owned" means and the full path-by-path breakdown live in
# docs/KIT-MANIFEST.md (ADR-0007) — read that first if anything here is
# surprising. In short:
#   - Whole-file/whole-dir kit-owned paths are overwritten (added/updated,
#     never deleted — if upstream removes a file, CHANGELOG.md calls it out
#     and you remove it by hand).
#   - .claude/, .github/agents/, .github/skills/, .codex/ are regenerated by
#     re-running mirror-agents.sh / mirror-skills.sh against the *updated*
#     .agents/, not copied from the source directly.
#   - .githooks/pre-commit(.ps1) and .github/workflows/agent-harness.yml are
#     partially kit-owned: only the text between `# === KIT:BEGIN ===` and
#     `# === KIT:END ===` is replaced; everything outside those markers (your
#     stack-specific lint/test/CI steps) is left exactly as you wrote it.
#   - Everything else (AGENTS.md, memory/, specs/, src/, tests/, your own ADRs,
#     the stack sections of hooks/CI) is never touched.
#
# Usage:
#   scripts/update-kit.sh <path-to-newer-kit-checkout> [--dry-run] [--yes]
#
# <path-to-newer-kit-checkout> is a local directory containing the kit at the
# version you want to update to — e.g.:
#   git clone https://github.com/<kit-org>/spec-driven-development /tmp/sdd-kit
#   git -C /tmp/sdd-kit checkout v0.2.0
#   scripts/update-kit.sh /tmp/sdd-kit
#
# --dry-run   Print what would change; write nothing.
# --yes       Skip the confirmation prompt.
#
# Run this on a clean git working tree. It writes files as it goes rather than
# staging everything atomically, so if it dies partway through (e.g. a
# corrupted KIT:BEGIN/KIT:END marker) some paths may already be updated. On a
# clean tree that's a non-issue: `git checkout -- .` (or `git status`/`git
# diff` to see exactly what changed) gets you back to a known state before you
# fix the flagged file and re-run.
#
# Cross-platform twin: update-kit.ps1 — both must implement the same
# kit-owned path list. Keep them in sync with docs/KIT-MANIFEST.md.

set -euo pipefail

die() { echo "✖ $*" >&2; exit 1; }
info() { echo "  $*"; }

ROOT="$(git rev-parse --show-toplevel 2>/dev/null || pwd)"
cd "$ROOT"

SRC=""
DRY_RUN=0
ASSUME_YES=0
for arg in "$@"; do
  case "$arg" in
    --dry-run) DRY_RUN=1 ;;
    --yes|-y)  ASSUME_YES=1 ;;
    -*)        die "unknown flag '$arg'" ;;
    *)         [ -z "$SRC" ] || die "unexpected extra argument '$arg'"; SRC="$arg" ;;
  esac
done
[ -n "$SRC" ] || die "usage: $0 <path-to-newer-kit-checkout> [--dry-run] [--yes]"
[ -d "$SRC" ] || die "'$SRC' is not a directory."
SRC="$(cd "$SRC" && pwd)"

[ -f "$SRC/VERSION" ] || die "'$SRC' has no VERSION file — is it a kit checkout?"
[ -f "VERSION" ] || die "this project has no VERSION file yet. Copy '$SRC/VERSION' in manually the first time (see docs/KIT-MANIFEST.md), then re-run."

CUR_VERSION="$(tr -d '[:space:]' < VERSION)"
NEW_VERSION="$(tr -d '[:space:]' < "$SRC/VERSION")"

if [ "$CUR_VERSION" = "$NEW_VERSION" ]; then
  echo "Already on kit version $CUR_VERSION — nothing to do."
  exit 0
fi

echo "Updating kit: $CUR_VERSION → $NEW_VERSION"
echo "Source: $SRC"
[ "$DRY_RUN" -eq 1 ] && echo "(dry run — no files will be written)"
echo ""

if [ "$ASSUME_YES" -ne 1 ] && [ "$DRY_RUN" -ne 1 ]; then
  read -r -p "This overwrites kit-owned paths (see docs/KIT-MANIFEST.md). Continue? [y/N] " reply
  case "$reply" in
    y|Y|yes|YES) ;;
    *) echo "Aborted."; exit 1 ;;
  esac
fi

run() {
  if [ "$DRY_RUN" -eq 1 ]; then
    echo "  [dry-run] $*"
  else
    "$@"
  fi
}

# ── 1. Whole-file kit-owned paths (added/updated) ───────────────────────────
KIT_OWNED_FILES=(
  VERSION
  CHANGELOG.md
  docs/KIT-MANIFEST.md
  .mcp.json.example
  .gitattributes
  LICENSE
  scripts/mirror-agents.sh
  scripts/mirror-agents.ps1
  scripts/mirror-skills.sh
  scripts/mirror-skills.ps1
  scripts/quiet.sh
  scripts/quiet.ps1
  scripts/update-kit.sh
  scripts/update-kit.ps1
  docs/README.md
  docs/context-engineering.md
  docs/harness-engineering.md
  docs/adaptive-workflow-and-extensions.md
  docs/token-efficiency.md
  docs/model-selection-and-token-optimization-in-sdd.md
  docs/efficient-code-generation-and-performance-pitfalls.md
  docs/mcp.md
  docs/hooks.md
  docs/guardrails.md
  docs/implementation-handoff.md
)

echo "── Kit-owned files"
for f in "${KIT_OWNED_FILES[@]}"; do
  [ -f "$SRC/$f" ] || continue
  run mkdir -p "$(dirname "$f")"
  if [ -f "$f" ] && cmp -s "$SRC/$f" "$f"; then
    continue
  fi
  info "$f"
  run cp "$SRC/$f" "$f"
done

# ── 2. Whole-dir kit-owned paths (merge: add/update, never delete) ─────────
KIT_OWNED_DIRS=(
  .agents/agents
  .agents/skills
  .agents/extensions
  templates
)

echo "── Kit-owned directories (add/update only, nothing deleted)"
for d in "${KIT_OWNED_DIRS[@]}"; do
  [ -d "$SRC/$d" ] || continue
  info "$d/"
  run mkdir -p "$d"
  run cp -R "$SRC/$d/." "$d/"
done

# The kit's own ADRs: any ADR filename that exists in the source is kit-owned
# and gets added/updated by filename; project-authored ADR filenames (which
# won't collide with upstream numbering — see docs/KIT-MANIFEST.md) are left
# alone because this only ever adds/overwrites files present in $SRC.
if [ -d "$SRC/docs/adr" ]; then
  echo "── Kit's own ADRs (docs/adr/, matched by filename)"
  run mkdir -p docs/adr
  for f in "$SRC"/docs/adr/*.md; do
    [ -e "$f" ] || continue
    base="$(basename "$f")"
    if [ -f "docs/adr/$base" ] && cmp -s "$f" "docs/adr/$base"; then
      continue
    fi
    info "docs/adr/$base"
    run cp "$f" "docs/adr/$base"
  done
fi

# ── 3. Partially kit-owned files: replace only the KIT:BEGIN..KIT:END block ─
merge_kit_section() {
  local target="$1" source="$2"
  [ -f "$source" ] || { info "(skip $target — not present in source)"; return; }
  [ -f "$target" ] || { info "$target (new file from kit)"; run cp "$source" "$target"; return; }

  for f in "$target" "$source"; do
    local begins ends
    begins=$(grep -c 'KIT:BEGIN ===' "$f")
    ends=$(grep -c 'KIT:END ===' "$f")
    if [ "$begins" -ne 1 ] || [ "$ends" -ne 1 ]; then
      die "$f: expected exactly one KIT:BEGIN/KIT:END marker pair, found $begins/$ends — resolve by hand (docs/KIT-MANIFEST.md), then re-run."
    fi
  done

  local tmp
  tmp="$(mktemp)"
  awk '
    /KIT:BEGIN ===/ { print; exit }
    { print }
  ' "$target" > "$tmp.prefix"
  awk '
    seen_begin { print }
    /KIT:BEGIN ===/ { seen_begin=1 }
  ' "$source" > "$tmp.middle"
  # trim $tmp.middle down to (and including) KIT:END, dropping anything after
  awk '
    { print }
    /KIT:END ===/ { exit }
  ' "$tmp.middle" > "$tmp.middle2"
  awk '
    seen_end { print }
    /KIT:END ===/ { seen_end=1 }
  ' "$target" > "$tmp.suffix"

  cat "$tmp.prefix" "$tmp.middle2" "$tmp.suffix" > "$tmp"
  rm -f "$tmp.prefix" "$tmp.middle" "$tmp.middle2" "$tmp.suffix"

  if cmp -s "$tmp" "$target"; then
    rm -f "$tmp"
    return
  fi
  info "$target (kit-owned section updated, your stack section preserved)"
  if [ "$DRY_RUN" -eq 1 ]; then
    rm -f "$tmp"
  else
    mv "$tmp" "$target"
    chmod --reference="$source" "$target" 2>/dev/null || chmod +x "$target" 2>/dev/null || true
  fi
}

echo "── Partially kit-owned hook/CI files"
merge_kit_section ".githooks/pre-commit"                    "$SRC/.githooks/pre-commit"
merge_kit_section ".githooks/pre-commit.ps1"                "$SRC/.githooks/pre-commit.ps1"
merge_kit_section ".github/workflows/agent-harness.yml"     "$SRC/.github/workflows/agent-harness.yml"

echo ""
if [ "$DRY_RUN" -eq 1 ]; then
  echo "Dry run complete. Re-run without --dry-run to apply."
  exit 0
fi

# ── 4. Regenerate generated mirrors from the updated .agents/ ──────────────
echo "── Regenerating .claude/.github/.codex mirrors"
r