#!/usr/bin/env bash
# update-kit.sh — pull kit-owned changes from a newer kit version into this
# project, without ever touching project-owned paths.
#
# The kit-owned path list this reads from is .agents/kit-manifest.conf — see
# that file for the full path-by-path breakdown if anything here is
# surprising. In short:
#   - Whole-file/whole-dir kit-owned paths are overwritten (added/updated,
#     never deleted — if upstream removes a file, KIT-CHANGELOG.md calls it
#     out and you remove it by hand).
#   - .claude/, .github/agents/, .github/skills/, .codex/ are regenerated by
#     re-running mirror-agents.sh / mirror-skills.sh against the *updated*
#     .agents/, not copied from the source directly.
#   - A `partial=<path>` entry in .agents/kit-manifest.conf (if any are ever
#     defined) means only the text between `# === KIT:BEGIN ===` and
#     `# === KIT:END ===` is replaced; everything outside those markers is
#     left exactly as you wrote it. Nothing currently uses this namespace —
#     .githooks/pre-commit(.ps1) and .github/workflows/agent-harness.yml used
#     to, but a CI workflow file isn't opt-in the way a git hook is (GitHub
#     auto-runs anything under .github/workflows/ the moment it's committed),
#     so both were dropped from the manifest. They still exist in this repo
#     for the kit's own use; copy them into your project by hand if you want
#     them, and they're yours to maintain from that point on.
#   - Everything else (AGENTS.md, memory/, specs/, src/, tests/, your own ADRs,
#     and anything not listed in kit-manifest.conf) is never touched.
#
# Usage:
#   scripts/update-kit.sh <path-to-newer-kit-checkout> [--dry-run] [--yes] [--force]
#
# <path-to-newer-kit-checkout> is a local directory containing the kit at the
# version you want to update to — e.g.:
#   git clone https://github.com/<kit-org>/spec-driven-development /tmp/sdd-kit
#   git -C /tmp/sdd-kit checkout v0.2.0
#   scripts/update-kit.sh /tmp/sdd-kit
#
# --dry-run   Print what would change; write nothing.
# --yes       Skip the confirmation prompt.
# --force     Allow the update to proceed even if the source checkout's
#             KIT_VERSION is semver-older than the one installed here (see
#             "Downgrade guard" below).
#
# Atomicity: every partially kit-owned file (any `partial=` entry in
# kit-manifest.conf — none ship by default, see above) has its KIT:BEGIN/
# KIT:END pair validated, in BOTH this project's copy and the source
# checkout's copy, before step 1 writes anything at all. A corrupted marker
# anywhere aborts the whole run up front with nothing changed on disk — you no
# longer need a clean tree as a safety net for that failure mode, though it's
# still good practice (`git status`/`git diff` before running, `git checkout
# -- .` to bail out) in case a later step fails for some other reason (disk
# full, permissions, etc).
#
# Downgrade guard: KIT_VERSION is compared as semver (major.minor.patch), not
# string inequality — pointing this at an older kit checkout is refused
# rather than silently downgrading. Pass --force if that's actually what you
# want (e.g. deliberately reverting to a prior kit release).
#
# Cross-platform twin: update-kit.ps1 — both must implement the same
# kit-owned path list. Neither hand-maintains that list any more: both read
# it from .agents/kit-manifest.conf in the SOURCE checkout at run time (see
# that file for the format), so there is nothing left to hand-sync between
# the two scripts — only the data file needs to change.

set -euo pipefail

die() { echo "✖ $*" >&2; exit 1; }
info() { echo "  $*"; }

ROOT="$(git rev-parse --show-toplevel 2>/dev/null || pwd)"
cd "$ROOT"

SRC=""
DRY_RUN=0
ASSUME_YES=0
FORCE=0
for arg in "$@"; do
  case "$arg" in
    --dry-run) DRY_RUN=1 ;;
    --yes|-y)  ASSUME_YES=1 ;;
    --force)   FORCE=1 ;;
    -*)        die "unknown flag '$arg'" ;;
    *)         [ -z "$SRC" ] || die "unexpected extra argument '$arg'"; SRC="$arg" ;;
  esac
done
[ -n "$SRC" ] || die "usage: $0 <path-to-newer-kit-checkout> [--dry-run] [--yes] [--force]"
[ -d "$SRC" ] || die "'$SRC' is not a directory."
SRC="$(cd "$SRC" && pwd)"

[ -f "$SRC/KIT_VERSION" ] || die "'$SRC' has no KIT_VERSION file — is it a kit checkout?"
[ -f "KIT_VERSION" ] || die "this project has no KIT_VERSION file yet. Copy '$SRC/KIT_VERSION' in manually the first time, then re-run."

CUR_VERSION="$(tr -d '[:space:]' < KIT_VERSION)"
NEW_VERSION="$(tr -d '[:space:]' < "$SRC/KIT_VERSION")"

if [ "$CUR_VERSION" = "$NEW_VERSION" ]; then
  echo "Already on kit version $CUR_VERSION — nothing to do."
  exit 0
fi

# ── Semver comparison — refuse a silent downgrade ───────────────────────────
version_parts() {
  local v="$1" a b c
  v="${v#v}"
  v="${v%%[-+]*}"
  IFS='.' read -r a b c <<< "$v"
  [[ "$a" =~ ^[0-9]+$ ]] || a=0
  [[ "$b" =~ ^[0-9]+$ ]] || b=0
  [[ "$c" =~ ^[0-9]+$ ]] || c=0
  printf '%s %s %s' "$a" "$b" "$c"
}

version_lt() {
  local a1 a2 a3 b1 b2 b3
  read -r a1 a2 a3 <<< "$(version_parts "$1")"
  read -r b1 b2 b3 <<< "$(version_parts "$2")"
  if [ "$a1" -ne "$b1" ]; then [ "$a1" -lt "$b1" ]; return; fi
  if [ "$a2" -ne "$b2" ]; then [ "$a2" -lt "$b2" ]; return; fi
  [ "$a3" -lt "$b3" ]
}

if [ "$FORCE" -ne 1 ] && version_lt "$NEW_VERSION" "$CUR_VERSION"; then
  die "'$SRC' is on kit version $NEW_VERSION, older than the installed $CUR_VERSION — refusing to downgrade. Pass --force if this is intentional (e.g. deliberately reverting to a prior release)."
fi

echo "Updating kit: $CUR_VERSION → $NEW_VERSION"
echo "Source: $SRC"
[ "$DRY_RUN" -eq 1 ] && echo "(dry run — no files will be written)"
echo ""

# Kit-owned path lists live in data (.agents/kit-manifest.conf), not code —
# see that file for the format. Read from the SOURCE checkout: the newer kit
# version's manifest decides what this run pulls in, same as KIT_VERSION. This is
# the same pattern as .agents/model-map.conf for mirror-agents.sh: the script
# just reads it, so there's nothing left to hand-sync between update-kit.sh
# and update-kit.ps1 (or the doc) — only the data file needs to change.
KIT_MANIFEST_CONF="$SRC/.agents/kit-manifest.conf"
[ -f "$KIT_MANIFEST_CONF" ] || die "$KIT_MANIFEST_CONF not found — '$SRC' predates the kit-manifest.conf convention, or isn't a kit checkout."

KIT_OWNED_FILES=()
KIT_OWNED_DIRS=()
KIT_ADR_DIRS=()
KIT_PARTIAL_FILES=()
while IFS='=' read -r ns path; do
  ns="$(printf '%s' "$ns" | sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//')"
  [ -z "$ns" ] && continue
  case "$ns" in \#*) continue ;; esac
  path="$(printf '%s' "$path" | sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//')"
  [ -z "$path" ] && continue
  case "$ns" in
    file)    KIT_OWNED_FILES+=("$path") ;;
    dir)     KIT_OWNED_DIRS+=("$path") ;;
    adr_dir) KIT_ADR_DIRS+=("$path") ;;
    partial) KIT_PARTIAL_FILES+=("$path") ;;
    *) die "$KIT_MANIFEST_CONF: unknown namespace '$ns' (expected file/dir/adr_dir/partial)" ;;
  esac
done < "$KIT_MANIFEST_CONF"
# No assertion on KIT_PARTIAL_FILES being non-empty — the partial= namespace
# is currently unused by default (see the header comment above); an empty
# list just means the loops below do nothing, which is correct.

validate_kit_markers() {
  local target="$1" source="$2"
  [ -f "$source" ] || return 0
  [ -f "$target" ] || return 0
  local f begins ends
  for f in "$target" "$source"; do
    begins=$(grep -c 'KIT:BEGIN ===' "$f" || true)
    ends=$(grep -c 'KIT:END ===' "$f" || true)
    if [ "$begins" -ne 1 ] || [ "$ends" -ne 1 ]; then
      die "$f: expected exactly one KIT:BEGIN/KIT:END marker pair, found $begins/$ends — resolve by hand, then re-run. Nothing has been written yet."
    fi
  done
}

if [ "${#KIT_PARTIAL_FILES[@]}" -gt 0 ]; then
  echo "── Validating kit-owned markers (before writing anything)"
  for f in "${KIT_PARTIAL_FILES[@]}"; do
    validate_kit_markers "$f" "$SRC/$f"
  done
fi

if [ "$ASSUME_YES" -ne 1 ] && [ "$DRY_RUN" -ne 1 ]; then
  read -r -p "This overwrites kit-owned paths. Continue? [y/N] " reply
  case "$reply" in
    y|Y|yes|YES) ;;
    *) echo "Aborted."; exit 1 ;;
  esac
fi

run() {
  if [ "$DRY_RUN" -eq 1 ]; then
    echo "  [dry-run] $*"
  else
    "$@"
  fi
}

echo "── Kit-owned files"
if [ "${#KIT_OWNED_FILES[@]}" -gt 0 ]; then
  for f in "${KIT_OWNED_FILES[@]}"; do
    [ -f "$SRC/$f" ] || continue
    run mkdir -p "$(dirname "$f")"
    if [ -f "$f" ] && cmp -s "$SRC/$f" "$f"; then
      continue
    fi
    info "$f"
    run cp "$SRC/$f" "$f"
  done
fi

echo "── Kit-owned directories (add/update only, nothing deleted)"
if [ "${#KIT_OWNED_DIRS[@]}" -gt 0 ]; then
  for d in "${KIT_OWNED_DIRS[@]}"; do
    [ -d "$SRC/$d" ] || continue
    info "$d/"
    run mkdir -p "$d"
    run cp -R "$SRC/$d/." "$d/"
  done
fi

if [ "${#KIT_ADR_DIRS[@]}" -gt 0 ]; then
  for adr_dir in "${KIT_ADR_DIRS[@]}"; do
    [ -d "$SRC/$adr_dir" ] || continue
    echo "── Kit's own ADRs ($adr_dir/, matched by filename)"
    run mkdir -p "$adr_dir"
    for f in "$SRC/$adr_dir"/*.md; do
      [ -e "$f" ] || continue
      base="$(basename "$f")"
      if [ -f "$adr_dir/$base" ] && cmp -s "$f" "$adr_dir/$base"; then
        continue
      fi
      info "$adr_dir/$base"
      run cp "$f" "$adr_dir/$base"
    done
  done
fi

merge_kit_section() {
  local target="$1" source="$2"
  [ -f "$source" ] || { info "(skip $target — not present in source)"; return; }
  [ -f "$target" ] || { info "$target (new file from kit)"; run cp "$source" "$target"; return; }

  for f in "$target" "$source"; do
    local begins ends
    begins=$(grep -c 'KIT:BEGIN ===' "$f" || true)
    ends=$(grep -c 'KIT:END ===' "$f" || true)
    if [ "$begins" -ne 1 ] || [ "$ends" -ne 1 ]; then
      die "$f: expected exactly one KIT:BEGIN/KIT:END marker pair, found $begins/$ends — resolve by hand, then re-run."
    fi
  done

  local tmp
  tmp="$(mktemp)"
  awk '
    /KIT:BEGIN ===/ { print; exit }
    { print }
  ' "$target" > "$tmp.prefix"
  awk '
    seen_begin { print }
    /KIT:BEGIN ===/ { seen_begin=1 }
  ' "$source" > "$tmp.middle"
  awk '
    { print }
    /KIT:END ===/ { exit }
  ' "$tmp.middle" > "$tmp.middle2"
  awk '
    seen_end { print }
    /KIT:END ===/ { seen_end=1 }
  ' "$target" > "$tmp.suffix"

  cat "$tmp.prefix" "$tmp.middle2" "$tmp.suffix" > "$tmp"
  rm -f "$tmp.prefix" "$tmp.middle" "$tmp.middle2" "$tmp.suffix"

  if cmp -s "$tmp" "$target"; then
    rm -f "$tmp"
    return
  fi
  info "$target (kit-owned section updated, your stack section preserved)"
  if [ "$DRY_RUN" -eq 1 ]; then
    rm -f "$tmp"
  else
    mv "$tmp" "$target"
    chmod --reference="$source" "$target" 2>/dev/null || chmod +x "$target" 2>/dev/null || true
  fi
}

if [ "${#KIT_PARTIAL_FILES[@]}" -gt 0 ]; then
  echo "── Partially kit-owned hook/CI files"
  for f in "${KIT_PARTIAL_FILES[@]}"; do
    merge_kit_section "$f" "$SRC/$f"
  done
fi

echo ""
if [ "$DRY_RUN" -eq 1 ]; then
  echo "Dry run complete. Re-run without --dry-run to apply."
  exit 0
fi

echo "── Regenerating .claude/.github/.codex mirrors"
bash scripts/mirror-agents.sh
bash scripts/mirror-skills.sh

echo ""
echo "Kit updated: $CUR_VERSION → $NEW_VERSION"
echo "Next steps:"
echo "  1. Review the diff: git status; git diff"
echo "  2. Read KIT-CHANGELOG.md's new entries for anything that needs manual follow-up"
echo "     (e.g. a new required AGENTS.md section, a template field you should backfill)."
echo "  3. Run your test suite, then commit."
